### ISSUE TITLE
Authentication is not working on uport mobile app

### ISSUE THREAD

**Issue by HamzaBinSarfraz** [uport-project/uportlandia#11]
i am scanning QRCode from uport landia [https://uportlandia.uport.me/city](url)
but nothing seems to happen on uport mobile app

**Comment by mirceanis** [comment]
It is an [issue of the mobile app](https://github.com/uport-project/uport-mobile/issues/209); there is already a fix which will be available in the next version of the app that is being published now.

EDIT:
It seems this was also affected but a fix was created in #12 
For a full fix, please upgrade uport-mobile to 1.6.482 or later.
